// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqs3gQiD2gbMY4k2k3HYAbroSemcN4Us8',
    appId: '1:602700996466:web:8c0621dae6ac653e65c7eb',
    messagingSenderId: '602700996466',
    projectId: 'ecommerceapp-254e1',
    authDomain: 'ecommerceapp-254e1.firebaseapp.com',
    storageBucket: 'ecommerceapp-254e1.firebasestorage.app',
    measurementId: 'G-PWGN71WJSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrNxCzfIhANXQ99be1o1MKjkl-pl03-c',
    appId: '1:602700996466:android:1ea413c22cf31e6465c7eb',
    messagingSenderId: '602700996466',
    projectId: 'ecommerceapp-254e1',
    storageBucket: 'ecommerceapp-254e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPpwWcRwzkprTHqWYF302zzT8xslllXYI',
    appId: '1:602700996466:ios:6cfb98b80ed7b3f965c7eb',
    messagingSenderId: '602700996466',
    projectId: 'ecommerceapp-254e1',
    storageBucket: 'ecommerceapp-254e1.firebasestorage.app',
    androidClientId: '602700996466-h1bbt4j5g66jvst7pc89f3093e63jmu0.apps.googleusercontent.com',
    iosClientId: '602700996466-mlioqrd73bf2rb6no5lm3hfuk0padl4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPpwWcRwzkprTHqWYF302zzT8xslllXYI',
    appId: '1:602700996466:ios:6cfb98b80ed7b3f965c7eb',
    messagingSenderId: '602700996466',
    projectId: 'ecommerceapp-254e1',
    storageBucket: 'ecommerceapp-254e1.firebasestorage.app',
    androidClientId: '602700996466-h1bbt4j5g66jvst7pc89f3093e63jmu0.apps.googleusercontent.com',
    iosClientId: '602700996466-mlioqrd73bf2rb6no5lm3hfuk0padl4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqs3gQiD2gbMY4k2k3HYAbroSemcN4Us8',
    appId: '1:602700996466:web:8af5ad8409404c2565c7eb',
    messagingSenderId: '602700996466',
    projectId: 'ecommerceapp-254e1',
    authDomain: 'ecommerceapp-254e1.firebaseapp.com',
    storageBucket: 'ecommerceapp-254e1.firebasestorage.app',
    measurementId: 'G-T8GBVS5K2Z',
  );

}